export enum EActionTypes {
  GET_ERRORS = "GET_ERRORS",
  SET_CURRENT_USER = "SET_CURRENT_USER",
  GET_USER = "GET_USER",
  USERS_LOADING = "USERS_LOADING",
  PROFILE_LOADING = "PROFILE_LOADING",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE",
  GET_USERS = "GET_USERS",
  CLEAR_ERRORS = "CLEAR_ERRORS"
}

export interface IAction {
  payload: any;
  type: EActionTypes;
}
